config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'memories#index'
  resources :memories, only: [ :index, :show, :new, :create] do
    resources :sharings, only: :create
  end
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :memories, only: :index
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user

  def name
    @name ||= "#{first_name} #{last_name}"
  end
end

app/models/memory.rb
class Memory < ApplicationRecord
  belongs_to :user
  has_many :memory_contacts, dependent: :destroy
  has_many :contacts, through: :memory_contacts
  has_many :sharings

  has_secure_token

  mount_base64_uploader :photo, PhotoUploader

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  validates :title, presence: :true, length: { maximum: 45 }

  include PgSearch
  pg_search_scope :global_search,
                  against: [:title, :address],
                  ignoring: :accents,
                  using: {
                    tsearch: { prefix: true }
                  }
end

app/models/memory_contact.rb
class MemoryContact < ApplicationRecord
  belongs_to :memory
  belongs_to :contact
end

app/models/sharing.rb
class Sharing < ApplicationRecord
  belongs_to :user
  belongs_to :memory

  validates :token, presence: true

  before_validation :check_token
  before_validation :check_user

  private

  def check_token
    errors.add(:token, "is invalid") unless memory&.token == token
  end

  def check_user
    errors.add(:user, "can't be memory's owner") if user == memory&.user
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :memories
  has_many :contacts
  has_many :sharings
end

app/controllers/api/v1/memories_controller.rb
class Api::V1::MemoriesController < ApplicationController
  def index
    memories = policy_scope(Memory).global_search(params[:query])
    memories = memories.map do |memory|
      {
        id: memory.id,
        title: memory.title,
        photo_url: memory.photo_url,
        url: memory_path(memory),
        address: memory.address
      }
    end
    render json: memories, status: :ok
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  include Pundit

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  def default_url_options
    { host: ENV["HOST"] || "localhost:3000" }
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/memories_controller.rb
class MemoriesController < ApplicationController
  before_action :set_memory, only: [ :show, :update, :destroy]

  def index
    @memories = policy_scope(Memory)
  end

  def show
    @marker = [{
      lat: @memory.latitude,
      lng: @memory.longitude,
      infoWindow: { content: render_to_string(partial: "/memories/map_box", locals: { memory: @memory }) }
    }]
    @sharings = @memory.sharings.includes(:user)
  end

  def new
    @memory = Memory.new
    authorize @memory
    if params[:latitude] && params[:longitude]
      @address = Geocoder.search([params[:latitude], params[:longitude]]).first&.data&.[]('formatted_address')
      @marker = [{
        lat: params[:latitude],
        lng: params[:longitude]
      }]
    end
    render layout: "naked"
  end

  def create
    @memory = Memory.new(memory_params)
    @memory.user = current_user
    authorize @memory
    if @memory.save
      redirect_to memories_path
    else
      @marker = [{
        lat: @memory.latitude,
        lng: @memory.longitude
      }]
      render :new
    end
  end

  def destroy

  end

private

  def set_memory
    @memory = Memory.find(params[:id])
    set_sharing if params[:token]
    authorize @memory
  end

  def memory_params
    params.require(:memory).permit(:title, :photo, :photo_cache, :address)
  end

  def set_sharing
    @sharing = Sharing.first_or_create(user: current_user, memory: @memory, token: params[:token])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/memory_helper.rb
module MemoryHelper
  include CloudinaryHelper

  def thumb_background(uploader)
    "background: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(\"#{image_path uploader.url(:thumb)}\");background-size: cover;"
  end
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">
    <%= favicon_link_tag %>
    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag 'map' %>
  </body>
</html>

app/views/layouts/naked.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Ram Access Memories</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag 'map' %>
    <%= yield :after_js %>
  </body>
</html>

app/views/memories/_map_box.html.erb
<div class='text-dark'>
  <%= memory.address %>
</div>

app/views/memories/_share_popover.html.erb
<div class="share-popover">
  <a href="sms://?body=Hello I want to share you a memory on pensine <%= memory_url(memory, token: memory.token) %>">
     <i class="mdi mdi-message-text-outline mdi-24px" aria-hidden="true"></i>
  </a>
  <a href="whatsapp://send?text=Hello I want to share you a memory on pensine <%= memory_url(memory, token: memory.token) %>">
     <i class="mdi mdi-whatsapp mdi-24px" aria-hidden="true"></i>
  </a>
  <a href="https://www.facebook.com/sharer/sharer.php?<%= { u: memory_url(memory, token: memory.token), t: memory.title, src: 'sdkpreparse' }.to_query %>"
     target="_blank"
     title="FB">
    <i class="mdi mdi-facebook mdi-24px" aria-hidden="true"></i>
  </a>
  <a href="mailto:">
    <i class="mdi mdi-gmail mdi-24px" aria-hidden="true"></i>
  </a>
</div>

app/views/memories/index.html.erb
<div class="cards-xs">
  <% @memories.each do |memory| %>
    <div class="card-xs" style='<%= thumb_background(memory.photo) %>'>
      <div class="text-center"><%= memory.title %></div>
      <%= link_to '', memory_path(memory), class: 'card-link' %>
    </div>
  <% end %>
</div>

app/views/memories/new.html.erb
<div class="camera">
  <video id="video">Video stream not available.</video>
  <div class="text-center camera-action" id="startbutton">
    <i class="mdi mdi-camera mdi-48px" aria-hidden="true"></i>
  </div>
</div>
<canvas id="canvas">
</canvas>
<div class="output">
  <div class="hidden" id="photo-box">
    <img id="photo" alt="The screen capture will appear in this box.">
    <div class="text-center camera-action" id="resetbutton">
      <i class="mdi mdi-close-circle-outline mdi-48px" aria-hidden="true"></i>
    </div>
  </div>
</div>
<div class="container text-center padded-1em">
  <%= simple_form_for @memory do |f| %>
    <%= f.input :title, hint: '45 characters max.' %>
    <%= f.input :photo, as: :hidden %>
    <%= f.input :photo_cache, as: :hidden %>
    <%= f.input :address, input_html: { value: @memory.address ||= @address } %>
    <%= f.submit "Save", class: "btn btn-full-width btn-primary" %>
  <% end %>
</div>
<% if @marker %>
  <div id="card-map"
    style="height: 300px;width:100%"
    data-markers="<%= @marker.to_json %>">
  </div>
<% end %>

<%= javascript_pack_tag 'camera' %>

app/views/memories/show.html.erb
<div class="card">
  <div class="card-image-box">
    <%= cl_image_tag @memory.photo_url, class: "card-image" %>
    <div class="card-share">
      <span href='#'
            data-container="body"
            data-toggle="popover"
            data-placement="bottom"
            data-html=true
            data-content='<%= render "memories/share_popover", memory: @memory %>'>
        <i class="mdi mdi-share-variant mdi-24px" aria-hidden="true"></i>
      </span>
    </div>
  </div>
  <div class="card-content">
    <%= @memory.title %>
    <p><%= pluralize(@sharings.count, 'share') %></p>
  </div>
  <% unless (@memory.latitude.nil? || @memory.latitude.nil?) %>
    <div id="card-map"
      style="height: 300px;"
      data-markers="<%= @marker.to_json %>">
    </div>
  <% end %>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <div class="searchbar navbar-wagon-item">
    <div id="searchbar"></div>
    <div id="search-button">
       <i class="mdi mdi-magnify mdi-36px" aria-hidden="true"></i>
    </div>
  </div>
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "aries-symbol.svg", height: 36 %>
  <% end %>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <%= link_to new_memory_path, class: 'navbar-wagon-link', id: 'add-memory',
      data: { target_url: new_memory_url } do %>
       <i class="mdi mdi-plus mdi-48px" aria-hidden="true"></i>
    <% end %>
  </div>
</div>